### ISSUE TITLE
TimeBeat CM4 module does not fit Waveshare PoE board

### ISSUE THREAD

**Issue by SM0VXI** [jclark/rpi-cm4-ptp-guide#21]
I just bought the Waveshare CM4 PoE Board, and a TimeBeat module. 

It seems the TimeBeat modules do not fit the Waveshare PoE board, due to the protrusion to the left for the SIT modules (as mentioned on the 'GPS receiver hardware options' page in this guide).

Since both the Waveshare board and the TimeBeat modules are discussed as possible hardware options in the guide, I thought it might be worth mentioning that they unfortunately don't fit together.

**Comment by jclark** [comment]
That would be a good thing to mention. Thanks for the suggestion.
