### ISSUE TITLE
Support for linuxptp v4?

### ISSUE THREAD

**Issue by yxie20** [jclark/rpi-cm4-ptp-guide#33]
Thank you for a fantastic guide.

I run into this issue when trying to run linuxptp v4.2, the same as: https://github.com/raspberrypi/linux/issues/5947#issuecomment-1946234727. In particular, ts2phc runs fine while ptp4l prints this message
```
ptp4l[932.128]: timed out while polling for tx timestamp
ptp4l[932.128]: increasing tx_timestamp_timeout may correct this issue, but it is likely caused by a driver bug
```

I'm not sure how to fix this. The reason I ask is because I'd like to use a higher baud rate, and the support is only added in a later version of linuxptp.

**Comment by jclark** [comment]
See https://github.com/jclark/rpi-cm4-ptp-guide/issues/23#issuecomment-2053885689

**Comment by dttromricks** [comment]
For what its worth to those looking to get linux ptp 4.2+ working on a CM4, with a timebeat mini card, i found i could make the tx timestamp problem noted above go away by setting this in the ptp4l.conf file:

`twoStepFlag             0`

not sure if https://www.mail-archive.com/linuxptp-devel@lists.sourceforge.net/msg06374.html is the 'real' the solution or not (or if it will ever be implemented.)

incidentally - i was able to get to 4.2 by adding the trixie repo to my bookwork system and then adding a pin to my apt preferences like so

```
# cat /etc/apt/preferences.d/trixie-pin 
Package: *
Pin: release n=trixie
Pin-Priority: -10

Package: linuxptp
Pin: release n=trixie
Pin-Priority: 501   
```

and then i installed the updated linux ptp with 
`
apt install -t trixie linuxptp
`
someday maybe I'll just dist-upgrade the whole thing in the normal way. 

Also worth noting that I installed 4.2 over 3.1.1 to get around the same issue Jeff Geerling mentioned above.  #geerlingguy/time-pi/issues/14

**Comment by jclark** [comment]
That's an interesting point about twoStepFlag. Thanks! I haven't experimented with that yet.

FWIW, I found it straightforward to upgrade my bookworm installations to trixie (although mine are fairly vanilla).

ptp_minor_version is the proper fix and is in 4.x. See https://satpulse.net/setup/ptp4l.html
